### ISSUE TITLE
error: unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by hyperJJmaster** [Pink-Silver/PyDoom#2]
help me!

**Comment by wallabra** [comment]
Just wanted to remind that PyDoom isn't a complete source port, it's just an attempt, as far as I know. I have made quite some progress at it on my fork using pure Python, but still nothing that can be runned.

I'm sorry if I am going blunt or something. I don't know about Visual C++ stuff so I can't help. :P

**Comment by reyzuleta** [comment]
mmmmm ok

**Comment by hyperJJmaster** [comment]
ok
